name: Checkout Example

on: workflow_dispatch
jobs:
  checkout-repository:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v3

         
